import { Inter, Lato } from "next/font/google";
import "../globals.css"
import Header from "@/components/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({ subsets: ["latin"] , weight: ['400' , '700'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main>
          <Header />
          <div className = "p-6 max-w-4xl mx-auto">
          {children}
          </div>
        </main>
        </body>
    </html>
  );
}
